pretrained_model_path: "./checkpoints/stable-diffusion-v1-5"
output_dir: "./outputs/slam_synthetic"

train_data:
  video_dir: "/work/zura-storage/Data/DrivingSceneDDM/"
  train_list: "/work/zura-storage/Workspace/DgTDM/dataset_scripts/train_short.txt"
  n_sample_frames: 24
  width: 128 
  height: 128
  sample_start_idx: 0
  sample_frame_rate: 2

validation_data:
  prompts:
    - "A vehicle driving in-road in a small town with a river and several bridges; rainly, cloudy town surroundings"
    - "A vehicle driving in-road in a busy metropolitan environment with skyscrapers; sunny noon city surroundings"
    - "A vehicle driving in-road in a real-world residential neighborhood, consists mainly with houses with garden and side parking cars; sunny noon urban surroundings"
    - "A vehicle driving in-road in a real-world less concentrated part of a city, cloudy noon city surroundings"
  start_depth_file:
    - "/work/zura-storage/Data/DrivingSceneDDM/depth/carla_01/000000.npy"
    - "/work/zura-storage/Data/DrivingSceneDDM/depth/gta_01/000000.npy"
    - "/work/zura-storage/Data/DrivingSceneDDM/depth/kitti_01/0000000000.npy"
    - "/work/zura-storage/Data/DrivingSceneDDM/depth/nus_01/000000.npy"
  start_canny_file:
    - "/work/zura-storage/Data/DrivingSceneDDM/canny/carla_01/000000.png"
    - "/work/zura-storage/Data/DrivingSceneDDM/canny/gta_01/000000.png"
    - "/work/zura-storage/Data/DrivingSceneDDM/canny/kitti_01/0000000000.png"
    - "/work/zura-storage/Data/DrivingSceneDDM/canny/nus_01/000000.png"
  video_length: 24
  width: 128
  height: 128
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: False
  num_inv_steps: 50

#learning_rate: 3e-5
learning_rate: 1e-4
train_batch_size: 2
max_train_steps: 20000
checkpointing_steps: 100
validation_steps: 1
trainable_modules:
  - "temporal_conv"
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"
  - "rel_pos_bias"

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
gradient_accumulation_steps: 50
use_offset_noise: False
offset_noise_strength: 0.1
use_depth: False

resume_from_checkpoint: "outputs/slam_synthetic/checkpoint-400"
# resume_from_checkpoint: "latest"
